truncate awebdesk_block;
delete from awebdesk_bounce_code where id > 48;
truncate awebdesk_bounce_data;
delete from awebdesk_bounce_list where listid != 1;
delete from awebdesk_branding where groupid != 3;
truncate awebdesk_campaign;
truncate awebdesk_campaign_list;
truncate awebdesk_campaign_mailer;
truncate awebdesk_campaign_message;
update awebdesk_cron set lastrun = null;
truncate awebdesk_cron_log;
#truncate awebdesk_exclusion;
delete from awebdesk_exclusion_list WHERE listid > 1;
#truncate awebdesk_exclusion_list;
truncate awebdesk_filter;
truncate awebdesk_filter_group;
truncate awebdesk_filter_group_cond;
truncate awebdesk_filter_list;
delete from awebdesk_form where id != 1000;
truncate awebdesk_form_list;
truncate awebdesk_forward;
delete from awebdesk_group where id > 3;
truncate awebdesk_group_field;
truncate awebdesk_group_field_rel;
truncate awebdesk_group_field_value;
delete from awebdesk_group_limit where groupid > 3;
delete from awebdesk_group_mailer where groupid > 3;
truncate awebdesk_header;
truncate awebdesk_header_list;
truncate awebdesk_link;
truncate awebdesk_link_action;
truncate awebdesk_link_data;
truncate awebdesk_link_log;
delete from awebdesk_list where id > 1;
truncate awebdesk_list_field_value;
delete from awebdesk_list_group where groupid > 3 or listid > 1;
truncate awebdesk_log;
#truncate awebdesk_message;
#truncate awebdesk_message_file;
#truncate awebdesk_message_file_data;
delete from awebdesk_message_list where listid > 1;
#truncate awebdesk_message_list;
	truncate awebdesk_outline;
	truncate awebdesk_outline_list;
delete from awebdesk_personalization_list where listid > 1;
truncate awebdesk_process;
truncate awebdesk_rssfeed;
truncate awebdesk_section_filter;
delete from awebdesk_subscriber where id > 9;
truncate awebdesk_subscriber_action;
truncate awebdesk_subscriber_action_part;
truncate awebdesk_subscriber_filter;
delete from awebdesk_subscriber_list where listid > 1 or subscriberid > 9;
truncate awebdesk_subscriber_responder;
delete from awebdesk_template_list where listid > 1;
truncate awebdesk_trapperrlogs;
delete from awebdesk_user where id > 1;
truncate awebdesk_user_b_log;
delete from awebdesk_user_group where userid != 1 or groupid NOT IN (1,2,3);
delete from awebdesk_user_p where userid != 1 and listid != 1;
delete from aweb_globalauth where id > 1;